on: [push]
# env:
#   MATHWORKS_LICENSING_ENDPOINT: stage
jobs: 
  my-job-v2-rc:
    name: Run Tests V2
    strategy:
      matrix:
        # Run this workflow on different os
        os: [windows-2022, ubuntu-22.04, macos-12]
        # release: [r2023a, r2023b]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.release }}
          products: Simulink Simulink_Test

      - name: Run command
        uses: matlab-actions/run-command@v1
        with:
          command: disp("hello world!")
          startup-options: -nojvm
          
      # Runs a set of commands using the runners shell
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: code

      # Run MATLAB build tool
      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: clean mtest
